### ISSUE TITLE
While rendering static image getting below error in console

### ISSUE THREAD

**Issue by subodh2711** [adobe/aem-core-forms-components#194]
#### Logs taken while reproducing problem

`core-forms-components-runtime-all.lc-869b2e6f7eeda41ff8361b5e06d1b428-lc.js:5306 Uncaught TypeError: Cannot read properties of undefined (reading 'charAt')
    at Utils.readData (core-forms-components-runtime-all.lc-869b2e6f7eeda41ff8361b5e06d1b428-lc.js:5306:35)
    at core-forms-components-runtime-all.lc-869b2e6f7eeda41ff8361b5e06d1b428-lc.js:5343:53
    at Array.forEach (<anonymous>)
    at core-forms-components-runtime-all.lc-869b2e6f7eeda41ff8361b5e06d1b428-lc.js:5342:43
    at Array.forEach (<anonymous>)
    at core-forms-components-runtime-all.lc-869b2e6f7eeda41ff8361b5e06d1b428-lc.js:5339:32
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (core-forms-components-runtime-all.lc-869b2e6f7eeda41ff8361b5e06d1b428-lc.js:5335:23)`

**Comment by nit23uec** [comment]
this is fixed.
